# .github/workflows/ci.yml
name: ci

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 */6 *' # Runs every six months to see if a new version of Moodle was released

jobs:
  ci:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@main
    # Required if you plan to publish (uncomment the below)
    # secrets:
      # moodle_org_token: ${{ secrets.MOODLE_ORG_TOKEN }}
